## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
#
# Quarkus
#
quarkus.banner.enabled = false
quarkus.log.file.enable = true
quarkus.log.file.rotation.max-backup-index = 0


#
# Timeouts
#
quarkus.test.hang-detection-timeout=30s

#
# TLS / SSL
#
quarkus.http.port=8080
quarkus.http.ssl-port=8443
%dev.quarkus.http.port=8280
%dev.quarkus.http.ssl-port=8643

quarkus.http.test-port=8180
quarkus.http.test-ssl-port=8543

quarkus.tls.trust-all=true


#
# CXF
#
quarkus.cxf.path=/cxf/services

quarkus.cxf.endpoint."/customer".wsdl = wsdl/CustomerService.wsdl
quarkus.cxf.endpoint."/customer".features = org.apache.cxf.ext.logging.LoggingFeature
quarkus.cxf.codegen.wsdl2java.customer-params.includes = wsdl/CustomerService.wsdl
quarkus.cxf.codegen.wsdl2java.customer-params.additional-params = -b,src/main/resources/binding.xml,-wsdlLocation,classpath:wsdl/CustomerService.wsdl

quarkus.cxf.endpoint."/contact".wsdl = wsdl/ContactService.wsdl
quarkus.cxf.endpoint."/contact".features = org.apache.cxf.ext.logging.LoggingFeature
quarkus.cxf.codegen.wsdl2java.contact-params.includes = wsdl/ContactService.wsdl
quarkus.cxf.codegen.wsdl2java.contact-params.additional-params = -b,src/main/resources/binding.xml,-wsdlLocation,classpath:wsdl/ContactService.wsdl

#
# Camel
#
camel.context.name = camel-quarkus-examples-cxf-soap


#
# Security Elytron with properties File
#
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.TestUser=testPw
#quarkus.security.users.embedded.roles.TestUser=testRole

##
## Kubernetes
##
## https://github.com/quarkusio/quarkus/issues/29209
#quarkus.kubernetes.image-pull-policy=IfNotPresent
#quarkus.kubernetes.ports."http".host-port=8080